Implementazione comando /abbandona
softeng2223-inf-uniba/progetto2223-lecun pull request #74
Opened 2023-06-04 17:39 UTC by JOHNEHOPCROFT

Implementazione del comando /abbandona il quale, una volta invocato, chiede conferma all'utente. Se la conferma è positiva mostra la posizione di tutte le navi sulla griglia e termina la partita, se la conferma è negativa prosegue la partita.
closes #59

2023-06-05 13:19 UTC, mattparadis requested changes
La Gradle build è fallita perchè alla riga 150 c'è un errore di battitura: Sistem.in invece di System.in. Inoltre dovresti aggiungere il comando abbandona nel metodo gestisciComandi in App.java.

2023-06-08 15:37 UTC, mattparadis commented
Cercando di risolvere alcuni conflitti per il merge del codice si sono creati degli errori, che ho provveduto a risolvere. Ora il codice è funzionante e il merge è possibile

2023-06-08 15:37 UTC, Luca803 approved these changes
Ok perfetto, ora non ci sono più problemi ed è tutto apposto

2023-06-08 15:37 UTC, mattparadis approved these changes

2023-06-08 15:37 UTC, merged