Correzione problema #3 sprint 1: Manuale utente
softeng2223-inf-uniba/progetto2223-lecun pull request #83
Opened 2023-06-09 10:41 UTC by leomoro1

Inserimento dei nuovi comandi all'interno del manuale e di screenshot di ciascun comando.
closes #51

2023-06-13 16:55 UTC, Luca803 requested changes
Potresti ricaricare le immagini aggiornate nei metodi in cui è stato implementato l'uso dei colori?

2023-06-13 21:44 UTC, Luca803 reviewed
Le immagini sono state aggiornate correttamente, ma credo che tu abbia dimenticato di aggiornare comando_abbandona.png perchè mi esce ancora la versione vecchia, non so se è un problema solo mio

2023-06-13 23:27 UTC, leomoro1 commented
Si hai ragione, adesso aggiorno l'immagine relativa al comando /abbandona

2023-06-14 08:17 UTC, mattparadis requested changes
Le foto sono tutte correttamente aggiornate, tranne una, cioè quella del comando abbandona, che è ancora della versione senza colori. In più potresti aggiungere una foto di esempio di colpo e una di quando la nave è affondata

2023-06-14 10:07 UTC, Luca803 approved these changes
Ok, ora tutte le foto sono correttamente aggiornate

2023-06-14 10:32 UTC, mattparadis approved these changes
Perfetto, i cambiamenti e le aggiunte richieste sono state apportate

2023-06-14 10:52 UTC, merged